version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: sauce_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    environment:
      - PATH=/directory/bin:$PATH
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
